repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: poetry run black --check --diff
        types:  [python]

      - id: flake8
        name: flake8
        language: system
        entry: poetry run flake8
        types: [python]

      - id: pydoctyle
        name: pydocstyle
        language: system
        entry: poetry run pydocstyle
        types: [python]
