name: Pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --tag linthell --target ci
      - run: docker run -v $(pwd):/app linthell bash Taskfile.sh ci:on_pull_request